version: "2.1"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: swole-frontend:latest
    container_name: swole-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./.env:/app/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: swole-backend:latest
    container_name: swole-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./.env:/app/.env
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: swole-db
    ports:
      - 3306:3306
    secrets:
      - db-root-password
    volumes:
      - /var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=SwoleQuery_Fitness
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-root-password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  seeder:
    build:
      context: ./
      dockerfile: Dockerfile
    image: swole-seeder:latest
    container_name: swole-seeder
    volumes:
      - ./database:/app/database # Persist the marker file
      - ./.env:/app/.env
    depends_on:
      db:
        condition: service_healthy

secrets:
  db-root-password:
    file: ./.secrets/db-root-password.txt
